export interface Player {
  id: string
  name: string
  realName: string
  team: string
  teamSlug: string
  teamColor: string
  role: string
  roleType: "awper" | "rifler" | "igl" | "entry"
  kd: string
  adr: string
  image: string
  country: string
}

export interface Team {
  id: string
  slug: string
  name: string
  shortName: string
  color: string
  region: string
  description: string
  roster: string[]
}

export const teams: Team[] = [
  {
    id: "1",
    slug: "navi",
    name: "Natus Vincere",
    shortName: "NAVI",
    color: "#fbbf24",
    region: "CIS",
    description: "One of the most iconic CS organizations. NAVI continue to dominate with a reshaped roster heading into 2026.",
    roster: ["b1t", "im", "aleksib", "wonderful", "makazze"],
  },
  {
    id: "2",
    slug: "faze",
    name: "FaZe Clan",
    shortName: "FaZe",
    color: "#ef4444",
    region: "Europe",
    description: "International powerhouse FaZe Clan remains a top contender with karrigan leading one of the most experienced rosters in CS2.",
    roster: ["karrigan", "broky", "frozen", "elige", "twistzz"],
  },
  {
    id: "3",
    slug: "g2",
    name: "G2 Esports",
    shortName: "G2",
    color: "#ffffff",
    region: "Europe",
    description: "G2 Esports rebuilt around m0NESY and huNter, bringing in fresh talent to challenge for the top spot in 2026.",
    roster: ["monesy", "hunter", "sunpayus", "heavygod", "matys"],
  },
  {
    id: "4",
    slug: "vitality",
    name: "Team Vitality",
    shortName: "VIT",
    color: "#fbbf24",
    region: "Europe",
    description: "Team Vitality, led by ZywOo, continue to be a force in global CS2 with an aggressive and well-rounded playstyle.",
    roster: ["zywoo", "apex", "flamez", "mezii", "jack"],
  },
  {
    id: "5",
    slug: "spirit",
    name: "Team Spirit",
    shortName: "SPR",
    color: "#f97316",
    region: "CIS",
    description: "Team Spirit rose to the #1 ranking in early 2025 behind superstar donk. They continue to push for major titles.",
    roster: ["donk", "sh1ro", "tn1r", "magixx", "zont1x"],
  },
  {
    id: "6",
    slug: "mouz",
    name: "MOUZ",
    shortName: "MOUZ",
    color: "#ef4444",
    region: "Europe",
    description: "MOUZ have been consistently improving and are now one of the elite teams in CS2 with a young and hungry roster.",
    roster: ["torzsi", "jimpphat", "xertioN", "siuhy", "boros"],
  },
]

export const players: Player[] = [
  {
    id: "b1t",
    name: "b1t",
    realName: "Valeriy Vakhovskiy",
    team: "NAVI",
    teamSlug: "navi",
    teamColor: "#fbbf24",
    role: "Rifler",
    roleType: "rifler",
    kd: "1.12",
    adr: "78.3",
    image: "/images/players/b1t.jpg",
    country: "Ukraine",
  },
  {
    id: "im",
    name: "iM",
    realName: "Mihai Ivan",
    team: "NAVI",
    teamSlug: "navi",
    teamColor: "#fbbf24",
    role: "Rifler",
    roleType: "rifler",
    kd: "1.08",
    adr: "74.1",
    image: "/images/players/im.jpg",
    country: "Romania",
  },
  {
    id: "aleksib",
    name: "Aleksib",
    realName: "Aleksi Virolainen",
    team: "NAVI",
    teamSlug: "navi",
    teamColor: "#fbbf24",
    role: "IGL",
    roleType: "igl",
    kd: "0.95",
    adr: "65.8",
    image: "/images/players/aleksib.jpg",
    country: "Finland",
  },
  {
    id: "wonderful",
    name: "w0nderful",
    realName: "Ihor Zhdanov",
    team: "NAVI",
    teamSlug: "navi",
    teamColor: "#fbbf24",
    role: "AWPer",
    roleType: "awper",
    kd: "1.18",
    adr: "72.5",
    image: "/images/players/wonderful.jpg",
    country: "Ukraine",
  },
  {
    id: "makazze",
    name: "makazze",
    realName: "Drin Shaqiri",
    team: "NAVI",
    teamSlug: "navi",
    teamColor: "#fbbf24",
    role: "Entry Fragger",
    roleType: "entry",
    kd: "1.05",
    adr: "76.2",
    image: "/images/players/b1t.jpg",
    country: "Kosovo",
  },
  {
    id: "zywoo",
    name: "ZywOo",
    realName: "Mathieu Herbaut",
    team: "Vitality",
    teamSlug: "vitality",
    teamColor: "#fbbf24",
    role: "AWPer",
    roleType: "awper",
    kd: "1.32",
    adr: "85.1",
    image: "/images/players/zywoo.jpg",
    country: "France",
  },
  {
    id: "karrigan",
    name: "karrigan",
    realName: "Finn Andersen",
    team: "FaZe",
    teamSlug: "faze",
    teamColor: "#ef4444",
    role: "IGL",
    roleType: "igl",
    kd: "0.88",
    adr: "61.4",
    image: "/images/players/karrigan.jpg",
    country: "Denmark",
  },
  {
    id: "broky",
    name: "broky",
    realName: "Helvijs Saukants",
    team: "FaZe",
    teamSlug: "faze",
    teamColor: "#ef4444",
    role: "AWPer",
    roleType: "awper",
    kd: "1.15",
    adr: "71.9",
    image: "/images/players/broky.jpg",
    country: "Latvia",
  },
  {
    id: "donk",
    name: "donk",
    realName: "Danil Kryshkovets",
    team: "Spirit",
    teamSlug: "spirit",
    teamColor: "#f97316",
    role: "Rifler",
    roleType: "rifler",
    kd: "1.35",
    adr: "88.7",
    image: "/images/players/donk.jpg",
    country: "Russia",
  },
  {
    id: "sh1ro",
    name: "sh1ro",
    realName: "Dmitry Sokolov",
    team: "Spirit",
    teamSlug: "spirit",
    teamColor: "#f97316",
    role: "AWPer",
    roleType: "awper",
    kd: "1.22",
    adr: "73.4",
    image: "/images/players/sh1ro.jpg",
    country: "Russia",
  },
  {
    id: "monesy",
    name: "m0NESY",
    realName: "Ilya Osipov",
    team: "G2",
    teamSlug: "g2",
    teamColor: "#ffffff",
    role: "AWPer",
    roleType: "awper",
    kd: "1.28",
    adr: "82.3",
    image: "/images/players/monesy.jpg",
    country: "Russia",
  },
  {
    id: "hunter",
    name: "huNter-",
    realName: "Nemanja Kovac",
    team: "G2",
    teamSlug: "g2",
    teamColor: "#ffffff",
    role: "Rifler",
    roleType: "rifler",
    kd: "1.06",
    adr: "74.8",
    image: "/images/players/karrigan.jpg",
    country: "Bosnia",
  },
]

export const skins = [
  {
    id: "1",
    name: "AWP | Dragon Lore",
    rarity: "Covert",
    rarityColor: "#eb4b4b",
    float: 0.08,
    price: "$12,450.00",
    weapon: "AWP",
    image: "/images/skins/awp-dragon-lore.jpg",
  },
  {
    id: "2",
    name: "M4A4 | Howl",
    rarity: "Contraband",
    rarityColor: "#e4ae39",
    float: 0.15,
    price: "$6,899.00",
    weapon: "M4A4",
    image: "/images/skins/m4a4-howl.jpg",
  },
  {
    id: "3",
    name: "AK-47 | Asiimov",
    rarity: "Covert",
    rarityColor: "#eb4b4b",
    float: 0.28,
    price: "$45.99",
    weapon: "AK-47",
    image: "/images/skins/ak47-asiimov.jpg",
  },
  {
    id: "4",
    name: "AK-47 | Neon Rider",
    rarity: "Covert",
    rarityColor: "#eb4b4b",
    float: 0.03,
    price: "$89.99",
    weapon: "AK-47",
    image: "/images/skins/ak47-neon-rider.jpg",
  },
  {
    id: "5",
    name: "AWP | Fade",
    rarity: "Covert",
    rarityColor: "#eb4b4b",
    float: 0.01,
    price: "$2,150.00",
    weapon: "AWP",
    image: "/images/skins/awp-fade.jpg",
  },
  {
    id: "6",
    name: "M4A1-S | Hyper Beast",
    rarity: "Classified",
    rarityColor: "#d32ce6",
    float: 0.12,
    price: "$35.50",
    weapon: "M4A1-S",
    image: "/images/skins/m4a1s-hyper-beast.jpg",
  },
  {
    id: "7",
    name: "USP-S | Kill Confirmed",
    rarity: "Covert",
    rarityColor: "#eb4b4b",
    float: 0.22,
    price: "$62.99",
    weapon: "USP-S",
    image: "/images/skins/usps-kill-confirmed.jpg",
  },
  {
    id: "8",
    name: "Desert Eagle | Blaze",
    rarity: "Restricted",
    rarityColor: "#4b69ff",
    float: 0.006,
    price: "$450.00",
    weapon: "Desert Eagle",
    image: "/images/skins/deagle-blaze.jpg",
  },
]
